import jsPDF from 'jspdf';

const C = {
  green:'#1D9E75', greenLight:'#E1F5EE', greenDark:'#085041',
  red:'#E24B4A',   redLight:'#FCEBEB',   redDark:'#791F1F',
  amber:'#F59E0B', amberLight:'#FFFBEB', amberDark:'#92400E',
  pink:'#EC4899',  blue:'#3B82F6',
  bg:'#F8FAFC', border:'#E2E8F0',
  text1:'#0F172A', text2:'#475569', text3:'#94A3B8', white:'#FFFFFF',
};

const hex2rgb   = h => [parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
const setFill   = (d,h) => { const [r,g,b]=hex2rgb(h); d.setFillColor(r,g,b); };
const setStroke = (d,h) => { const [r,g,b]=hex2rgb(h); d.setDrawColor(r,g,b); };
const setColor  = (d,h) => { const [r,g,b]=hex2rgb(h); d.setTextColor(r,g,b); };

const fRect = (doc,x,y,w,h,r,fill,stroke) => {
  setFill(doc,fill);
  if (stroke) { setStroke(doc,stroke); doc.roundedRect(x,y,w,h,r,r,'FD'); }
  else        { doc.roundedRect(x,y,w,h,r,r,'F'); }
};

const rule = (doc,x,y,w,hex=C.border) => {
  setStroke(doc,hex); doc.setLineWidth(0.2); doc.line(x,y,x+w,y);
};

const safe = str => {
  if (typeof str !== 'string') return String(str ?? '');
  return str
    .replace(/β/g,'\xDF').replace(/≥/g,'>=').replace(/≤/g,'<=')
    .replace(/→/g,'->').replace(/[^\x00-\xFF]/g,'?');
};

const reportId = () => {
  const n=new Date(), p=x=>String(x).padStart(2,'0');
  return `TCP-${n.getFullYear()}${p(n.getMonth()+1)}${p(n.getDate())}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
};

const pct = v => typeof v==='number' ? `${Math.round(v*100)}%` : '—';
const fmt = (v,dp=2) => typeof v==='number' ? v.toFixed(dp) : '—';

const drawFooter = (doc,p,total,PW,PH,ML,MR) => {
  const fy=PH-16;
  setFill(doc,C.text1); doc.rect(0,fy+0.5,PW,16,'F');
  doc.setFont('helvetica','normal'); doc.setFontSize(6); setColor(doc,C.text3);
  doc.text(safe('This report is generated by ThalaPredict. Results do not replace clinical judgement. Confirmatory testing required.'),ML,fy+6);
  doc.text('Genetic counselling is strongly recommended for couples where both partners are identified as carriers.',ML,fy+10);
  doc.setFont('helvetica','bold'); setColor(doc,C.text3);
  doc.text('ThalaPredict v1.0 — Couple Screening', PW-MR, fy+6,  {align:'right'});
  doc.text(`Page ${p} of ${total}`,                PW-MR, fy+10, {align:'right'});
};

const partnerBlock = (doc, partnerData, result, label, accent, x, y, w) => {
  const isCarrier = result.prediction === 1;
  const resBg     = isCarrier ? C.redLight   : C.greenLight;
  const resBorder = isCarrier ? C.red        : C.green;
  const resDark   = isCarrier ? C.redDark    : C.greenDark;
  const H = 68;

  fRect(doc, x, y, w, H, 3, C.bg, C.border);

  // Accent top bar
  setFill(doc, accent); doc.roundedRect(x, y, w, 5, 2,2,'F');
  doc.rect(x, y+3, w, 2, 'F');

  doc.setFont('helvetica','bold'); doc.setFontSize(7); setColor(doc,C.white);
  doc.text(label, x+4, y+4);

  // Patient info
  doc.setFont('helvetica','normal'); doc.setFontSize(6.5); setColor(doc,C.text3);
  doc.text('Patient ID', x+4, y+12);
  doc.setFont('helvetica','bold'); setColor(doc,C.text1);
  doc.text(partnerData.patientId || 'Anonymous', x+w-4, y+12, {align:'right'});

  doc.setFont('helvetica','normal'); setColor(doc,C.text3);
  doc.text('Age / Sex', x+4, y+18);
  doc.setFont('helvetica','bold'); setColor(doc,C.text1);
  doc.text(`${partnerData.age || '—'} yrs / ${partnerData.sex || '—'}`, x+w-4, y+18, {align:'right'});

  if (partnerData.district) {
    doc.setFont('helvetica','normal'); setColor(doc,C.text3);
    doc.text('District', x+4, y+24);
    doc.setFont('helvetica','bold'); setColor(doc,C.text1);
    doc.text(partnerData.district, x+w-4, y+24, {align:'right'});
  }

  rule(doc, x+3, y+28, w-6);

  // Result badge
  fRect(doc, x+3, y+31, w-6, 16, 2, resBg, resBorder);
  doc.setFont('helvetica','bold'); doc.setFontSize(6); setColor(doc,isCarrier?C.red:C.green);
  doc.text(isCarrier ? 'CARRIER DETECTED' : 'NON-CARRIER', x+6, y+36);
  doc.setFontSize(11); setColor(doc,resDark);
  doc.text(result.label || (isCarrier?'Carrier':'Non-carrier'), x+6, y+43);
  doc.setFontSize(14); setColor(doc,isCarrier?C.red:C.green);
  doc.text(pct(result.carrier_probability), x+w-6, y+43, {align:'right'});
  doc.setFont('helvetica','normal'); doc.setFontSize(5.5); setColor(doc,C.text3);
  doc.text('carrier prob', x+w-6, y+47, {align:'right'});

  // Probability bar
  const bx=x+4, bw2=w-8;
  setFill(doc,C.border); doc.roundedRect(bx, y+51, bw2, 3, 1,1,'F');
  setFill(doc,isCarrier?C.red:C.green);
  doc.roundedRect(bx, y+51, bw2*(result.carrier_probability||0), 3, 1,1,'F');

  // Confidence
  doc.setFont('helvetica','normal'); doc.setFontSize(6); setColor(doc,C.text3);
  doc.text('Confidence:', x+4, y+60);
  const confC = result.confidence==='High' ? C.green : result.confidence==='Moderate' ? C.amber : C.red;
  fRect(doc, x+22, y+56.5, 18, 4.5, 1, confC, '');
  doc.setFont('helvetica','bold'); doc.setFontSize(6); setColor(doc,C.white);
  doc.text(result.confidence||'—', x+31, y+59.5, {align:'center'});

  if (result.referral_recommended) {
    fRect(doc, x+44, y+56.5, w-48, 4.5, 1, C.amberLight, '');
    doc.setFont('helvetica','bold'); doc.setFontSize(5.5); setColor(doc,C.amberDark);
    doc.text('Referral req.', x+44+(w-48)/2, y+59.5, {align:'center'});
  }

  // CBC values
  doc.setFont('helvetica','normal'); doc.setFontSize(5.5); setColor(doc,C.text3);
  const cbcY = y+H+3;
  fRect(doc, x, cbcY, w, 12, 2, C.white, C.border);
  ['MCV','MCH','HBG','RBC'].forEach((param,i) => {
    const cx = x+4 + i*(w-8)/4;
    const val = partnerData[param.toLowerCase()];
    doc.setFont('helvetica','normal'); setColor(doc,C.text3);
    doc.text(param, cx, cbcY+5);
    doc.setFont('helvetica','bold'); setColor(doc,C.text1);
    doc.text(val ? String(parseFloat(val).toFixed(1)) : '—', cx, cbcY+10);
  });

  return H + 16;
};

export const generateCoupleReport = async ({
  result, partnerA, partnerB, clinicianName='Clinician'
}) => {
  const doc  = new jsPDF({orientation:'portrait', unit:'mm', format:'a4'});
  const PW=210, PH=297, ML=14, MR=14, CW=PW-ML-MR;
  const now  = new Date();
  const dStr = now.toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'});
  const tStr = now.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
  const rid  = reportId();

  const { coupleRisk } = result;
  const bothCarriers   = coupleRisk.bothCarriers;
  const oneCarrier     = coupleRisk.oneCarrier;

  const riskColor  = bothCarriers ? C.red   : oneCarrier ? C.amber : C.green;
  const riskBg     = bothCarriers ? '#FCEBEB' : oneCarrier ? '#FFFBEB' : '#E1F5EE';
  const riskBorder = bothCarriers ? C.red   : oneCarrier ? C.amber : C.green;
  const riskDark   = bothCarriers ? C.redDark : oneCarrier ? C.amberDark : C.greenDark;

  let curY = 0;
  const SAFE_BOTTOM = PH - 26;
  const space   = () => SAFE_BOTTOM - curY;
  const newPage = () => { doc.addPage(); curY = 18; };

  //  HEADER 
  setFill(doc,C.text1); doc.rect(0,0,PW,22,'F');
  setFill(doc,C.green); doc.rect(0,0,5,22,'F');
  doc.setFont('helvetica','bold'); doc.setFontSize(14); setColor(doc,C.white);
  doc.text('ThalaPredict', ML, 10);
  doc.setFont('helvetica','normal'); doc.setFontSize(7.5); setColor(doc,C.text3);
  doc.text(safe('ß-Thalassemia Carrier Screening — Couple Report'), ML, 15.5);
  doc.setFontSize(7); setColor(doc,C.text3);
  doc.text(`Report ID: ${rid}`, PW-MR, 8,  {align:'right'});
  doc.text(`${dStr}  ${tStr}`,  PW-MR, 13, {align:'right'});
  doc.text(`Clinician: ${clinicianName}`, PW-MR, 18, {align:'right'});

  curY = 28;

  //  TITLE 
  doc.setFont('helvetica','bold'); doc.setFontSize(11); setColor(doc,C.text1);
  doc.text(safe('ß-Thalassemia Couple Screening Report'), ML, curY);
  doc.setFont('helvetica','normal'); doc.setFontSize(7.5); setColor(doc,C.text3);
  doc.text('Both partners screened simultaneously using SVM classifier  |  Mendelian risk assessment applied', ML, curY+5);
  rule(doc, ML, curY+8, CW); curY += 13;

  //  PARTNER BLOCKS SIDE BY SIDE 
  const HW = (CW-6)/2;
  const hA = partnerBlock(doc, partnerA, result.partnerA, 'PARTNER A', C.pink, ML,      curY, HW);
  const hB = partnerBlock(doc, partnerB, result.partnerB, 'PARTNER B', C.blue, ML+HW+6, curY, HW);
  curY += Math.max(hA, hB) + 8;

  // COUPLE RISK SUMMARY 
  if (space() < 60) newPage();

  const summaryLines = doc.splitTextToSize(safe(coupleRisk.summary), CW-14);
  const summaryH     = Math.max(28, summaryLines.length*4.8+18);

  fRect(doc, ML, curY, CW, summaryH, 3, riskBg, riskBorder);
  setFill(doc,riskColor); doc.roundedRect(ML,curY,3,summaryH,1,1,'F');

  doc.setFont('helvetica','bold'); doc.setFontSize(9); setColor(doc,riskColor);
  doc.text(
    bothCarriers ? 'HIGH RISK COUPLE — BOTH PARTNERS CARRIERS'
  : oneCarrier   ? 'ONE PARTNER IS A CARRIER'
  : 'NO CARRIER RISK IDENTIFIED',
    ML+8, curY+7
  );
  doc.setFont('helvetica','normal'); doc.setFontSize(6.5); setColor(doc,C.text3);
  doc.text('Mendelian inheritance risk assessment', ML+8, curY+12);
  doc.setFont('helvetica','normal'); doc.setFontSize(7); setColor(doc,C.text1);
  doc.text(summaryLines, ML+8, curY+18);
  curY += summaryH + 6;

  //  RISK PROBABILITY TILES 
  if (bothCarriers || oneCarrier) {
    if (space() < 28) newPage();

    const tiles = bothCarriers
      ? [{pct:25,label:'Affected child (thalassaemia major)',color:C.red},
         {pct:50,label:'Carrier child (thalassaemia minor)', color:C.amber},
         {pct:25,label:'Unaffected child',                   color:C.green}]
      : [{pct:0, label:'Affected child risk',                color:C.green},
         {pct:50,label:'Carrier child risk',                 color:C.amber},
         {pct:50,label:'Unaffected child',                   color:C.green}];

    const tw = (CW - (tiles.length-1)*4) / tiles.length;
    tiles.forEach(({pct:p,label,color},i) => {
      const tx = ML + i*(tw+4);
      fRect(doc, tx, curY, tw, 20, 2, C.bg, C.border);
      doc.setFont('helvetica','bold'); doc.setFontSize(14); setColor(doc,color);
      doc.text(`${p}%`, tx+tw/2, curY+12, {align:'center'});
      doc.setFont('helvetica','normal'); doc.setFontSize(6); setColor(doc,C.text2);
      doc.text(label, tx+tw/2, curY+17, {align:'center'});
    });
    curY += 26;
  }

  //  PUNNETT SQUARE (both carriers only) 
  if (bothCarriers) {
    if (space() < 50) newPage();

    doc.setFont('helvetica','bold'); doc.setFontSize(7.5); setColor(doc,C.text2);
    doc.text('PUNNETT SQUARE (Tt x Tt)', ML, curY+5);
    rule(doc, ML, curY+7, CW); curY += 11;

    const cells = [
      {label:'TT', sub:'Unaffected (25%)', bg:C.greenLight, color:C.greenDark},
      {label:'Tt', sub:'Carrier (50%)',    bg:C.amberLight, color:C.amberDark},
      {label:'Tt', sub:'Carrier (50%)',    bg:C.amberLight, color:C.amberDark},
      {label:'tt', sub:'Affected (25%)',   bg:C.redLight,   color:C.redDark},
    ];
    const cw2 = 36, ch = 20, gap = 4;
    const gridX = ML;

    // Headers
    doc.setFont('helvetica','bold'); doc.setFontSize(6.5); setColor(doc,C.text2);
    doc.text('T (Partner A)', gridX+cw2+gap+cw2/2,    curY-2, {align:'center'});
    doc.text('t (Partner A)', gridX+cw2+gap*2+cw2*1.5, curY-2, {align:'center'});

    cells.forEach((c,i) => {
      const col = i%2, row = Math.floor(i/2);
      const cx  = gridX + cw2+gap + col*(cw2+gap);
      const cy  = curY  + row*(ch+gap);

      // Row header
      if (col===0) {
        doc.setFont('helvetica','bold'); doc.setFontSize(6.5); setColor(doc,C.text2);
        doc.text(row===0 ? 'T (Partner B)' : 't (Partner B)', gridX+cw2-2, cy+ch/2+2, {align:'right'});
      }

      fRect(doc, cx, cy, cw2, ch, 2, c.bg, c.color);
      doc.setFont('helvetica','bold'); doc.setFontSize(14); setColor(doc,c.color);
      doc.text(c.label, cx+cw2/2, cy+12, {align:'center'});
      doc.setFont('helvetica','normal'); doc.setFontSize(6); setColor(doc,c.color);
      doc.text(c.sub, cx+cw2/2, cy+17, {align:'center'});
    });

    curY += 2*(ch+gap) + 6;

    doc.setFont('helvetica','italic'); doc.setFontSize(6.5); setColor(doc,C.text3);
    doc.text('T = normal allele  |  t = thalassaemia allele  |  tt = affected (thalassaemia major)', ML, curY);
    curY += 8;
  }

  //  REFERRAL BOX 
  if (space() < 20) newPage();

  const refText = safe(
    bothCarriers
      ? 'URGENT: Both partners confirmed as probable carriers. Immediate referral for genetic counselling and prenatal diagnosis required. Options include chorionic villus sampling (10-13 weeks) or amniocentesis (15-20 weeks).'
      : oneCarrier
      ? 'One partner is a probable carrier. Children have a 50% chance of being carriers but are not at risk for thalassaemia major. Genetic counselling is advised.'
      : 'Neither partner is identified as a carrier at current screening threshold. Routine clinical follow-up applies.'
  );
  const refLines = doc.splitTextToSize(refText, CW-14);
  const refH     = Math.max(22, refLines.length*4.8+14);

  fRect(doc, ML, curY, CW, refH, 3, bothCarriers?C.redLight:oneCarrier?C.amberLight:C.greenLight,
        bothCarriers?C.red:oneCarrier?C.amber:C.green);
  setFill(doc,riskColor); doc.roundedRect(ML,curY,3,refH,1,1,'F');
  doc.setFont('helvetica','bold'); doc.setFontSize(8); setColor(doc,riskDark);
  doc.text(bothCarriers ? 'URGENT REFERRAL REQUIRED' : oneCarrier ? 'REFERRAL ADVISED' : 'NO REFERRAL REQUIRED',
    ML+8, curY+7);
  doc.setFont('helvetica','normal'); doc.setFontSize(7); setColor(doc,C.text1);
  doc.text(refLines, ML+8, curY+13);
  curY += refH + 6;

  //  COUPLE SCREENING ID 
  if (space() < 14) newPage();
  fRect(doc, ML, curY, CW, 12, 2, C.bg, C.border);
  doc.setFont('helvetica','normal'); doc.setFontSize(6.5); setColor(doc,C.text3);
  doc.text('Couple Screening ID:', ML+4, curY+7);
  doc.setFont('helvetica','bold'); setColor(doc,C.text1);
  doc.text(result.coupleScreeningId || '—', ML+44, curY+7);
  curY += 16;

  // FOOTERS 
  const total = doc.internal.getNumberOfPages();
  for (let p=1; p<=total; p++) {
    doc.setPage(p);
    drawFooter(doc, p, total, PW, PH, ML, MR);
  }

  //  SAVE 
  const nameA = partnerA.patientId || 'PartnerA';
  const nameB = partnerB.patientId || 'PartnerB';
  doc.save(`ThalaPredict_Couple_${nameA}_${nameB}_${now.toISOString().slice(0,10)}.pdf`);
};